# Generated by Django 3.2.8 on 2021-10-27 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='mode',
            new_name='view',
        ),
    ]
